ktor:
  application:
    modules:
      - eu.filebridge.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:5173/"
  realm: "Filebridge API"
  secret: $JWT_SECRET
redis:
  keySchema:
    user: "user:"
    userList: "userList"
    file: "file:"
    owner: "owner:"
filebridge:
  maxFiles: 10